// <auto-generated />
using System;
using Interview_Question_Generator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview_Question_Generator.Migrations
{
    [DbContext(typeof(InterviewContext))]
    [Migration("20260315133805_MakeUserIdNullableTestSession")]
    partial class MakeUserIdNullableTestSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interview_Question_Generator.Models.AirequestLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("RequestTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__AIReques__5E5486481B8466AD");

                    b.HasIndex("UserId");

                    b.ToTable("AIRequestLogs");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD66B75B9EF");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.GeneratedQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId")
                        .HasName("PK__Generate__0DC06FACAD492331");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequestId");

                    b.ToTable("GeneratedQuestions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.QuestionCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Question__19093A0BCB86AF20");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Question__8517B2E065A05B45")
                        .IsUnique();

                    b.ToTable("QuestionCategories");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.QuestionRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Experience")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SourceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId")
                        .HasName("PK__Question__33A8517AF4449BE9");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestionRequests");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A22A60E9E");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160F3734CCD")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA09187FC76A23E");

                    b.HasIndex(new[] { "SkillName" }, "UQ__Skills__B63C65710FB4FE2F")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.TestSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserAnswersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__TestSess__C9F49290322990AE");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.UploadedMcqFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<int>("UploadedUserUserId")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.ToTable("UploadedMcqFiles");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C292A1E45");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105348B63627A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.UserSavedQuestion", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaveId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SaveId")
                        .HasName("PK__UserSave__1450D3A66C314662");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavedQuestions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.AirequestLog", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.User", "User")
                        .WithMany("AirequestLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AIRequest__UserI__01142BA1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Feedback", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.GeneratedQuestion", "Question")
                        .WithMany("Feedbacks")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Questi__787EE5A0");

                    b.HasOne("Interview_Question_Generator.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__UserId__778AC167");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.GeneratedQuestion", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.QuestionCategory", "Category")
                        .WithMany("GeneratedQuestions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Generated__Categ__6FE99F9F");

                    b.HasOne("Interview_Question_Generator.Models.QuestionRequest", "Request")
                        .WithMany("GeneratedQuestions")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__Generated__Reque__6EF57B66");

                    b.Navigation("Category");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.QuestionRequest", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.Skill", "Skill")
                        .WithMany("QuestionRequests")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__QuestionR__Skill__6B24EA82");

                    b.HasOne("Interview_Question_Generator.Models.User", "User")
                        .WithMany("QuestionRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__QuestionR__UserI__6A30C649");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.TestSession", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.Skill", "Skill")
                        .WithMany("TestSessions")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__TestSessi__Skill__7D439ABD");

                    b.HasOne("Interview_Question_Generator.Models.User", "User")
                        .WithMany("TestSessions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TestSessi__UserI__7C4F7684");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.User", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__60A75C0F");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.UserSavedQuestion", b =>
                {
                    b.HasOne("Interview_Question_Generator.Models.GeneratedQuestion", "Question")
                        .WithMany("UserSavedQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSaved__Quest__73BA3083");

                    b.HasOne("Interview_Question_Generator.Models.User", "User")
                        .WithMany("UserSavedQuestions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSaved__UserI__72C60C4A");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.GeneratedQuestion", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("UserSavedQuestions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.QuestionCategory", b =>
                {
                    b.Navigation("GeneratedQuestions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.QuestionRequest", b =>
                {
                    b.Navigation("GeneratedQuestions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.Skill", b =>
                {
                    b.Navigation("QuestionRequests");

                    b.Navigation("TestSessions");
                });

            modelBuilder.Entity("Interview_Question_Generator.Models.User", b =>
                {
                    b.Navigation("AirequestLogs");

                    b.Navigation("Feedbacks");

                    b.Navigation("QuestionRequests");

                    b.Navigation("TestSessions");

                    b.Navigation("UserSavedQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
