#!/bin/bash
# 1. To display all executable files, directories and zero sized files from current directory. 

echo "Executable files:"
find . -maxdepth 1 -type f -executable

echo
echo "Directories:"
find . -maxdepth 1 -type d

echo
echo "Zero-sized files:"
find . -maxdepth 1 -type f -size 0

