#!/bin/bash
# 2. To display the date, time, and a welcome message (like Good Morning etc.). The time should be 
# displayed with “a.m.” or “p.m.” and not in 24 hours notation. 

hour=$(date +"%I")
time=$(date +"%I:%M %p")
date_today=$(date +"%d-%m-%Y")

if [ "$hour" -lt 12 ]; then
    message="Good Morning"
elif [ "$hour" -lt 16 ]; then
    message="Good Afternoon"
else
    message="Good Evening"
fi

echo "Date: $date_today"
echo "Time: $time"
echo "$message"

